### ISSUE TITLE
Error: Validation Failed: "already_exists"

### ISSUE THREAD

**Issue by yngtdd** [loopwerk/tag-changelog#5]
I am running into a bit of a snag when setting up the changelog action on one of my repositories. I had previously created two releases before adding this Action, and it looks like I am hitting the following error:

```
Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

I am sure that this is user error. How should I setup the action to handle this? Here is a link to my [workflow](https://github.com/yngtdd/rusty_dungeon/blob/main/.github/workflows/changelog.yml).

<img width="1339" alt="Screen Shot 2022-03-29 at 2 30 16 PM" src="https://user-images.githubusercontent.com/84814700/160680751-7a09bb6c-d75d-4d52-afa3-284a986b45df.png">

**Comment by kevinrenskers** [comment]
It seems this error is generated by the action create-release, not tag-changelog. I'm not sure how to help you with this, to be honest. Your workflow seems to be identical to the one from my readme, so that should just work. It's the same config I use in multiple open source projects without problems.

Are you trying to push a tag that already has a matching release? In the error I see the tag `v0.1.3`, and in your repo I also see a release with that version. So how did you create that release?

**Comment by yngtdd** [comment]
I had manually created releases at `https://github.com/yngtdd/rusty_dungeon/releases/new`, naming both the tag and the release `v0.1.3` (similar with the earlier releases).

In the screenshot below, in the `Choose a Tag` drop down, I created a tag name `v0.1.3`, then named the `Release title` below that to `v0.1.3`. Perhaps I should delete those earlier releases and check the workflow? 

<img width="1477" alt="Screen Shot 2022-03-29 at 3 24 16 PM" src="https://user-images.githubusercontent.com/84814700/160691766-14a7372d-5773-40ff-89d6-7ff3a2c1521d.png">

**Comment by yngtdd** [comment]
Interesting, after deleting the previous releases and their associated tags, I get

```
Run loopwerk/tag-changelog@v1
  with:
    token: ***
    exclude_types: other,docs,chore
    config_file: .github/tag-changelog-config.js
Error: Couldn't find previous tag
```

Sorry for my ignorance here. Looks like I need to have an initial tag, but to avoid the previous issue where it was seeing that the tag already exists, should I name it something other than the semver convention? 

I see in the marketplace the following note:

```
Handle the very first tag - currently this Action only works when at least two tags are found
```

This is where I was getting the idea of creating a few initial tags, `v0.1.0, v0.1.2, v0.1.3`, but then was hitting the `"already_exists"` issue. 

<img width="1355" alt="Screen Shot 2022-03-29 at 3 34 22 PM" src="https://user-images.githubusercontent.com/84814700/160693074-6dc331f0-5ba7-425d-a551-17fabde0a5fc.png">

**Comment by kevinrenskers** [comment]
Well I am sure you can just ignore that error you got initially, and from now on when you push the first new tag (that doesn't already have a release), it shouldn't give an error anymore, right? 

So I think you should be good to push tag v0.1.3, ignore any errors, and when you're going to push v0.1.4 (which doesn't have a release), it shouldn't give any errors.

Closing this issue, as I don't think there's a real problem here. Please feel free to open a new issue when your upcoming tag is also going to give errors.
